- name: remove swap
  shell: "swapoff -a"

- name: TCP port 6443 on master is reachable from worker
  wait_for: "host={{ hostvars['master']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"
- name: join cluster
  shell: "{{ hostvars['master'].join_command }} >> node_joined.log"
  args:
    chdir: /home/kubeadmin
    creates: node_joined.log
